apiVersion: v1
kind: Service
metadata:
  name: orderer
spec:
  type: ClusterIP
  ports:
  - protocol: TCP
    port: 7050
    name: grpc
  selector:
    app: orderer
---
apiVersion: v1
kind: Service
metadata:
  name: orderer2
spec:
  type: ClusterIP
  ports:
  - protocol: TCP
    port: 7050
    name: grpc
  selector:
    app: orderer2
---
apiVersion: v1
kind: Service
metadata:
  name: orderer3
spec:
  type: ClusterIP
  ports:
  - protocol: TCP
    port: 7050
    name: grpc
  selector:
    app: orderer3
---
apiVersion: v1
kind: Service
metadata:
  name: orderer4
spec:
  type: ClusterIP
  ports:
  - protocol: TCP
    port: 7050
    name: grpc
  selector:
    app: orderer4
---
apiVersion: v1
kind: Service
metadata:
  name: orderer5
spec:
  type: ClusterIP
  ports:
  - protocol: TCP
    port: 7050
    name: grpc
  selector:
    app: orderer5