apiVersion: v1
kind: ConfigMap
metadata:
  name: peer0org1
data:
  CORE_PEER_ID: peer0org1
  CORE_PEER_ADDRESS: peer0org1:7051
  CORE_PEER_LISTENADDRESS: 0.0.0.0:7051
  CORE_PEER_CHAINCODEADDRESS: peer0org1:7052
  CORE_PEER_CHAINCODELISTENADDRESS: 0.0.0.0:7052
  CORE_PEER_GOSSIP_BOOTSTRAP: peer1org1:7051
  CORE_PEER_GOSSIP_EXTERNALENDPOINT: peer0org1:7051
  CORE_PEER_LOCALMSPID: Org1MSP
  CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS: localhost:5984
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: peer1org1
data:
  CORE_PEER_ID: peer1org1
  CORE_PEER_ADDRESS: peer1org1:7051
  CORE_PEER_LISTENADDRESS: 0.0.0.0:7051
  CORE_PEER_CHAINCODEADDRESS: peer1org1:7052
  CORE_PEER_CHAINCODELISTENADDRESS: 0.0.0.0:7052
  CORE_PEER_GOSSIP_EXTERNALENDPOINT: peer1org1:7051
  CORE_PEER_GOSSIP_BOOTSTRAP: peer0org1:7051
  CORE_PEER_LOCALMSPID: Org1MSP
  CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS: localhost:5984
---
apiVersion: v1
kind: Secret
metadata:
  name: couchdbpeer0org1
data:
  COUCHDB_USER: Y291Y2hkYlBlZXIwT3JnMQ==
  COUCHDB_PASSWORD: cHNzd3Jk
---
apiVersion: v1
kind: Secret
metadata:
  name: couchdbpeer1org1
data:
  COUCHDB_USER: Y291Y2hkYlBlZXIxT3JnMQ==
  COUCHDB_PASSWORD: cHNzd3Jk
---
apiVersion: v1
kind: Secret
metadata:
  name: couchdbpeer0org1access
data:
  CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME: Y291Y2hkYlBlZXIwT3JnMQ==
  CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD: cHNzd3Jk
---
apiVersion: v1
kind: Secret
metadata:
  name: couchdbpeer1org1access
data:
  CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME: Y291Y2hkYlBlZXIxT3JnMQ==
  CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD: cHNzd3Jk
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cliorg1
data:
  FABRIC_LOGGING_SPEC: INFO
  CORE_PEER_ADDRESS: peer0org1:7051
  CORE_PEER_ID: cliorg1
  CORE_PEER_LOCALMSPID: Org1MSP
  CORE_PEER_MSPCONFIGPATH: /opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/org1.example.com/users/Admin@org1.example.com/msp
  CORE_PEER_TLS_CERT_FILE: /opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/org1.example.com/peers/peer0.org1.example.com/tls/server.crt
  CORE_PEER_TLS_ENABLED: "true"
  CORE_PEER_TLS_KEY_FILE: /opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/org1.example.com/peers/peer0.org1.example.com/tls/server.key
  CORE_PEER_TLS_ROOTCERT_FILE: /opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/org1.example.com/peers/peer0.org1.example.com/tls/ca.crt
  GOPATH: /opt/gopath
  ORDERER_CA: /opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/ordererOrganizations/example.com/orderers/orderer.example.com/msp/tlscacerts/tlsca.example.com-cert.pem