apiVersion: apps/v1 
kind: Deployment
metadata:
  name: fabcar-org1
  labels:
    app: fabcar-org1
spec:
  selector:
    matchLabels:
      app: fabcar-org1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: fabcar-org1
    spec:
      containers:
        - image: library/nodejs-fabcar:1.0
          name: fabcar-org1
          imagePullPolicy: IfNotPresent
          env:
            - name: CORE_CHAINCODE_ID
              value: "fabcar:1e4ff6bbecf64ccc6ae6c9a8738827943da69de5b1e165762d9484b6134b1ebd"
            - name: CORE_CHAINCODE_ADDRESS
              value: "0.0.0.0:7052"
          ports:
            - containerPort: 7052
---
apiVersion: apps/v1 
kind: Deployment
metadata:
  name: fabcar-org2
  labels:
    app: fabcar-org2
spec:
  selector:
    matchLabels:
      app: fabcar-org2
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: fabcar-org2
    spec:
      containers:
        - image: library/nodejs-fabcar:1.0
          name: fabcar-org2
          imagePullPolicy: IfNotPresent
          env:
            - name: CORE_CHAINCODE_ID
              value: "fabcar:22713a8d18b1e0d90252c918786dfe37afb919dad5ee5b6ee9568e8a170d50eb"
            - name: CORE_CHAINCODE_ADDRESS
              value: "0.0.0.0:7052"
          ports:
            - containerPort: 7052