apiVersion: v1
kind: Service
metadata:
  name: fabcar-org1-svc
spec:
  selector:
    app: fabcar-org1
  type: ClusterIP
  ports:
  - port: 7052
    protocol: TCP
    name: grpc
---
apiVersion: v1
kind: Service
metadata:
  name: fabcar-org2-svc
spec:
  selector:
    app: fabcar-org2
  type: ClusterIP
  ports:
  - port: 7052
    protocol: TCP
    name: grpc
