apiVersion: v1
kind: Service
metadata:
  name: peer0org2
spec:
  type: ClusterIP
  ports:
  - protocol: TCP
    port: 7051
    name: grpc
  - protocol: TCP
    port: 5984
    name: couchdb
  selector:
    app: peer0org2
---    
apiVersion: v1
kind: Service
metadata:
  name: peer1org2
spec:
  type: ClusterIP
  ports:
  - protocol: TCP
    port: 7051
    name: grpc
  - protocol: TCP
    port: 5984
    name: couchdb
  selector:
    app: peer1org2