apiVersion: v1
kind: ConfigMap
metadata:
  name: ordererbase
data:
  FABRIC_LOGGING_SPEC: info
  ORDERER_GENERAL_LISTENADDRESS: 0.0.0.0
  ORDERER_GENERAL_GENESISMETHOD: file
  ORDERER_GENERAL_GENESISFILE: /var/hyperledger/orderer/genesis.block
  ORDERER_GENERAL_LOCALMSPID: OrdererMSP
  ORDERER_GENERAL_LOCALMSPDIR: /var/hyperledger/orderer/msp
  # enabled TLS
  ORDERER_GENERAL_TLS_ENABLED: "true"
  ORDERER_GENERAL_TLS_PRIVATEKEY: /var/hyperledger/orderer/tls/server.key
  ORDERER_GENERAL_TLS_CERTIFICATE: /var/hyperledger/orderer/tls/server.crt
  ORDERER_GENERAL_TLS_ROOTCAS: /var/hyperledger/orderer/tls/ca.crt
  ORDERER_GENERAL_CLUSTER_CLIENTCERTIFICATE: /var/hyperledger/orderer/tls/server.crt
  ORDERER_GENERAL_CLUSTER_CLIENTPRIVATEKEY: /var/hyperledger/orderer/tls/server.key
  ORDERER_GENERAL_CLUSTER_ROOTCAS: /var/hyperledger/orderer/tls/ca.crt