apiVersion: v1
kind: ConfigMap
metadata:
  name: peerbase
data:
  CORE_VM_ENDPOINT: http://localhost:2375
  FABRIC_LOGGING_SPEC: info
  CORE_PEER_TLS_ENABLED: "true"
  CORE_PEER_GOSSIP_USELEADERELECTION: "true"
  CORE_VM_DOCKER_ATTACHSTDOUT: "true"
  CORE_PEER_GOSSIP_ORGLEADER: "false"
  CORE_PEER_PROFILE_ENABLED: "true"
  CORE_PEER_TLS_CERT_FILE: /etc/hyperledger/fabric/tls/server.crt
  CORE_PEER_TLS_KEY_FILE: /etc/hyperledger/fabric/tls/server.key
  CORE_PEER_TLS_ROOTCERT_FILE: /etc/hyperledger/fabric/tls/ca.crt
  CORE_LEDGER_STATE_STATEDATABASE: CouchDB
  CORE_OPERATIONS_LISTENADDRESS: 0.0.0.0:9443